CREATE TABLE CAR_POSITION (
    PLATE VARCHAR(10) NOT NULL,
    POSITION_DATE TIMESTAMP NOT NULL,
    SPEED NUMBER DEFAULT 0,
    LONGITUDE NUMERIC(18, 10),
    LATITUDE NUMERIC(18, 10),
    IGNITION BOOLEAN NOT NULL,

    CONSTRAINT PK_POSITION PRIMARY KEY(PLATE, POSITION_DATE)
);

CREATE TABLE POINT_OF_INTEREST(
    POI_ID NUMBER NOT NULL,
    POI_NAME VARCHAR(100) NOT NULL,
    POI_RADIUS INTEGER NOT NULL,
    POI_LATITUDE NUMERIC(18, 15) NOT NULL,
    POI_LONGITUDE NUMERIC(18, 15) NOT NULL,

    CONSTRAINT PK_POI PRIMARY KEY(POI_ID)
);

CREATE SEQUENCE SEQ_POI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;